
Question.create(question: "Have you ever gotten a hurtful anonymous message?", info_image:"http://www.chicago-bureau.org/wp-content/uploads/2013/10/2013-03-05-shutterstock_108383702.jpg", info_text: "The funny part about cyber-bullying is that hardly anyone is totally innocent! Usually even targets of cyber-bullies have been mean to others online at some point. This means that everyone has been a bully, and everyone has been a victim. Remember to treat others the way you would expect to be treated, even if they're not being nice in the moment.", story_head:"Emily's Story", story_video:"https://www.youtube.com/embed/PltmyjazaZ0", story_text:"See how easy it is to get cought up in a cyberbullying situation.")

Question.create(question: "Have you ever seen a mean comment on the Internet and liked it or thought it was funny?", info_image:"http://cdn2.hubspot.net/hub/176530/file-18530139-jpg/images/cyberbullying1-resized-600.jpg", info_text: "Anonymous messages are hurtful because when you receive a mean message but don’t know who sent it, it can seem like EVERYONE feels that way about you. It can feel a lot worse than when you know who said it and why they feel that way. Before you send someone an anonymous message, or post a mean anonymous comment about someone, think about WHY you want to do that to them. If you have an issue with someone, try talking through it with them instead. It takes a lot of courage to discuss your problems face to face, but it’s much easier to understand each other that way. Remember, that nothing online is anonymous. Anything can be tracked on your phones, internet, and computers. Don't send anything anonymously, you could face criminal penalties for it later. If someone is bullying you anonymously, ask for an adult to help you trace the person behind it.", story_head:"Liz's Story", story_video:"https://www.youtube.com/embed/lriMD0-bLas", story_text:"Liz shares her story of annonymous bullying.")

Question.create(question: "Have you ever stuck up for someone who was being picked on?", info_image:"http://i.dailymail.co.uk/i/pix/2009/08/21/article-1208147-04B1C884000005DC-420_468x286.jpg", info_text:"When you show others its okay to stick up for someone who is being bullied, they are more likely to do it for someone else, or even you!", story_head:"Abby's Story", story_video:"https://www.youtube.com/embed/2YGjz5SV_Qk", story_text:"Abby bravely shares her story of getting bullied.")

Question.create(question: "Has anyone ever stuck up for you when you were being picked on?", info_image:"http://o.aolcdn.com/dims-shared/dims3/GLOB/crop/5173x3479+0+1/resize/620x413!/format/jpg/quality/85/http://o.aolcdn.com/hss/storage/adam/d4ce7e082816fed09d48d68afdfca01c/159225529.jpg", info_text: "Studies have shown, more than half the time bullies will stop within 10 seconds of being called out by someone else!", story_head:"Jake's Story", story_video:"https://www.youtube.com/embed/jMVOh7TcWaE", story_text:"Jake's story is one of the powerful narratives filmed for The BULLY Project, the social action campaign inspired by the documentary film BULLY.")

Question.create(question: "Have you ever felt like you might be physically hurt by others?", info_image:"http://media.philly.com/images/bully-600-827.jpg", info_text:"If you are in danger of being hurt, you need to let a trusted adult know, they can help keep you safe. 1 in 6 online teens say that they have been contacted online by someone they didn’t know in a way that made them feel scared or uncomfortable.", story_head:"Elloise's Story", story_video:"https://www.youtube.com/embed/04eWltMszDM", story_text:"Emily shares her story about being bullied.")

Question.create(question: "Do you feel like you have an adult you can talk to if you needed their help?", info_image:"http://www.worldmomsblog.com/wp-content/uploads/2012/07/bullying-research-image.jpg", info_text:"Often, people think they don’t need help from a parent or teacher, or they wouldn’t give them good advice. We’re trying to help adults know how to handle these situations better, but in the meantime, you should know that almost half of the teens who have seen online bullying have asked for advice about what to do- and almost 100% of them said that the advice they got was helpful! So even if you don’t want to talk to a parent or teacher- find someone you trust who makes good decisions and ask them what they would do!", story_head:"Colleen's Story", story_video:"https://www.youtube.com/embed/n5xoBoOec_E", story_text:"See Colleen talk about her story of getting bullied.")

Question.create(question: "Have you ever felt like getting revenge for something someone said to you?", info_image:"http://1da9f03rgzm732m9sv35cuvj.wpengine.netdna-cdn.com/wp-content/uploads/2011/03/bullying-header-large1.jpg", info_text:"Most people who end up being mean online are responding to something they were hurt by… How can we improve offline communication so that we break the cycle of online retaliation? Only YOU can tell someone that they hurt you, and only YOU can apologize for hurting someone else. If everyone thinks this way, there’s no need to take it online!", story_head:"Brooke's Story", story_video:"https://www.youtube.com/embed/NNxrcuqtnc0", story_text:"Watch Brooke tell her story of getting bullied.")

Question.create(question: "Do you think social media sites and apps like Instagram, Snapchat, Facebook, Kik, are places where bullying happens often?", info_image:"http://i.livescience.com/images/i/000/016/329/iFF/bullies-victim-110429.jpg?1304111590", info_text:"In one year, 1 million children reported being harassed, threatened, or subjected to other forms of cyberbullying on Facebook alone!", story_head:"Cassandra's Story", story_video:"https://www.youtube.com/embed/N16OYZBLnRE", story_text:"Watch Cassandra's story of getting bullied on and off line.")

Question.create(question: "Are your parents monitoring your cell phone and internet activity in any way?", info_image:"http://bloximages.newyork1.vip.townnews.com/stltoday.com/content/tncms/assets/v3/editorial/8/fe/8fed798b-bf81-5e27-84d3-9d5073b78799/52cc784414d71.preview-620.jpg", info_text:"Teens who aren’t being monitored by their parents are more likely to become involved in cyber bullying. Parents who have no idea what their kids are doing online don’t have the chance to understand the bullying situations you might come across. Talk to your parents about the sites you use and the choices you make- you may need their advice in the future!", story_head:"Amanda's Story", story_video:"https://www.youtube.com/embed/APxPalpJlTY", story_text:"See how Amanda handles getting cyberbullied.")

Question.create(question: "Do you think your parents have the right to monitor this activity?", info_image:"http://parental-control.biz/wp-content/uploads/2014/04/parents-compuyter.jpg", info_text:"Understand that parents have a right to check into your media history on your computer and phone and other devices such as iTouch, games and whatever else you use regularly, especially if your parents are paying for those devices or apps. They just want to keep you safe!", story_head:"Paul's Story", story_video:"https://www.youtube.com/embed/joIkjbK2fvg", story_text:"Watch Paul confess his story of getting bullied.")

Question.create(question: "Do you spend some time thinking about what you post about others on the internet or in text messages?", info_image:"http://img.opposingviews.com/sites/default/files/imagecache/402x250/featured_image/0215/monitoringsocialmedia_featured.jpg", info_text:"Next time you post something on the internet, read it twice and check for anything that might be misunderstood- delete it if its mean or think of another way to say it! We’re all responsible for making the Internet a safer place for each other! Online words have real-life consequences.", story_head:"Theodora's Story", story_video:"https://www.youtube.com/embed/L1BbUC2Uxp0", story_text:"Theodora speaks about getting bullied as a teen.")




Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_3.jpg")
Sign.create(sign_source: "sign_selfie_1.jpg")
Sign.create(sign_source: "sign_selfie_2.jpg")
Sign.create(sign_source: "sign_selfie_4.jpg")
